### ISSUE TITLE
Stream content from disk direct into encoder stream

### ISSUE THREAD

**Issue by gmaclennan** [noffle/blob-store-replication-stream#4]
We just received a [new error report](https://app.bugsnag.com/digital-democracy/mapeo-mobile/errors/5db088ad52cec0001aba7caf?event_id=5db088ad00511aa1aec90000&i=gh&m=ci) from Mapeo Mobile:

```
RangeError · Array buffer allocation failed
```

The stack trace only tells us that this was in `concat-stream`, and it seems like this error is due to being out of memory.

I searched through the bundle for Mapeo Mobile to see where we use concat-stream, and the most likely culprit (that would cause memory issues on a small phone) is here: https://github.com/noffle/blob-store-replication-stream/blob/master/index.js#L196

This _may_ be a one-off for this particular phone (that reported this error), but this is probably worth fixing anyway to avoid issues in the future (especially if we start using video = larger files. This might also be a cause of slowdown on sync since the garbage collector would be working hard with this.

**Comment by noffle** [comment]
I wonder if this was the core issue (too many allocs within BSRS) or just the straw that broke the camel's back + the phone was already on lowmem from other various things.

I don't really see how this could be the core issue. The code works by

1. loading the current single media file into memory
2. writes it to the length-prefixed encoder stream
3. explicitly checks to make sure the encoder stream isn't exerting backpressure (if so, it waits for a `drain` event)
4. proceeds to the next media file

The GC should be freeing up the media data in memory, since there is async space between everything for it to run, but I suppose it could just NOT be, for some reason. When I did a stress test on this code with thousands of large media files, the memory usage stayed relatively constant. It definitely didn't balloon like it used to.

Are you sure MM is running at least version `1.3.3`? That's when the backpressure fix got in.

**Comment by gmaclennan** [comment]
You're right - checking the error report this is from 1.1.0-beta.8 which was built in July, so it would not include that fix. I should get on an release the current alpha track as a new beta, or push a patch update to beta.9 to pull in this change.

A single file will probably be ok. Looking at some other error reports today it seems like the device was low on memory anyway.
